### ISSUE TITLE
Suggestion on the styling

### ISSUE THREAD

**Issue by Rahuletto** [ArmoredVortex/Startpage#2]
# Suggestion !
Hey, first of all i really like this concept. But some things could be done to make it more great ! What if the mouse blob color also changes according to the color you update ? Would be very great !

**Comment by Rahuletto** [comment]
As its a background gradient, you can use css variables to make it possible

**Comment by armoredvortex** [comment]
2230215bfabe54df68aa3a951deac50e8ca05ef0 Adds ability to select a custom blob color and maps the gradient with the primary color.

**Comment by Rahuletto** [comment]
Added yay
